apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-roks-cluster
spec:
  params:
    - name: cluster-name
      type: string
      description: New ROKS cluster name
    - name: git-new-roks-url
      type: string
      default: 'https://github.com/ocaso-demo/ibm-roks.git'
      description: GitHub url where the scripts to create a new ROKS cluster are for the pipeline to execute them.
    - name: git-new-roks-branch
      type: string
      default: main
      description: Github branch for the pipeline scripts
    - name: multi-tenancy-gitops-url
      type: string
      default: 'https://github.com/ocaso-demo/multi-tenancy-gitops.git'
      description: Multi-tenancy GitHub repository url where clusters are managed from.
    - name: multi-tenancy-gitops-branch
      type: string
      default: master
      description: Github branch for the multi-tenancy-gitops repo.
    - name: debug
      type: string
      default: "True"
      description: Debug flag
  tasks:
    - name: new-roks-create-cluster
      taskRef:
        name: new-roks-create-cluster
      params:
      # New ROKS Cluster name
      - name: cluster-name
        value: "$(params.cluster-name)"
      # GitHub url where the scripts to create a new ROKS cluster are for the pipeline to execute them.
      - name: git-new-roks-url
        value: "$(params.git-new-roks-url)"
      # Github branch for the pipeline scripts.
      - name: git-new-roks-branch
        value: "$(params.git-new-roks-branch)"
      # Debug flag
      - name: debug
        value: "$(params.debug)"
    - name: new-roks-import-cluster
      taskRef:
        name: new-roks-import-cluster
      runAfter:
        - new-roks-create-cluster
      params:
      # New cluster's name
      - name: cluster-name
        value: "$(tasks.new-roks-create-cluster.results.cluster-name)"
      # GitHub url where the scripts to create a new ROKS cluster are for the pipeline to execute them.
      - name: git-new-roks-url
        value: "$(params.git-new-roks-url)"
      # Github branch for the pipeline scripts.
      - name: git-new-roks-branch
        value: "$(params.git-new-roks-branch)"
      # Multi-tenancy GitHub repository url where clusters are managed from.
      - name: multi-tenancy-gitops-url
        value: "$(params.multi-tenancy-gitops-url)"
      # Github branch for the multi-tenancy-gitops repo.
      - name: multi-tenancy-gitops-branch
        value: "$(params.multi-tenancy-gitops-branch)"
      # Debug flag
      - name: debug
        value: "$(params.debug)"