apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-new-roks-cluster
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: new-roks-cluster
# subjects:
# - kind: ServiceAccount
#   name: tekton-new-roks-cluster
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: tekton-triggers-eventlistener-roles
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: new-roks-cluster
# subjects:
# - kind: ServiceAccount
#   name: tekton-new-roks-cluster
#   namespace: cicd
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: tekton-triggers-eventlistener-clusterroles

## THIS NEEDS TO BE REVISITED TO PROVIDE PROPERLY RESTRICTED PERMISSIONS
# See mq/environments/ci/roles
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: new-roks-cluster-tekton-event-listener
subjects:
- kind: ServiceAccount
  name: tekton-new-roks-cluster
  namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin