apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: new-roks-cluster-
spec:
  params:
    - name: cluster-name
      value: 'test-cluster-2'
    - name: git-new-roks-url
      value: 'https://github.com/ocaso-demo/ibm-roks.git'
    - name: git-new-roks-branch
      value: main
    - name: multi-tenancy-gitops-url
      value: 'https://github.com/ocaso-demo/multi-tenancy-gitops.git'
    - name: multi-tenancy-gitops-branch
      value: master
    - name: debug
      value: 'False'
  pipelineRef:
    name: new-roks-cluster
  serviceAccountName: pipeline
  timeout: 1h0m0s