apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-roks-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "350"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: ocaso/environments/cicd/new-roks-cluster/
    repoURL: https://github.com/ocaso-demo/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
