apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: new-roks-cluster
spec:
  params:
  - name: cluster-name
    default: ""
  - name: git-new-roks-url
    default: 'https://github.com/ocaso-demo/ibm-roks.git'
  - name: git-new-roks-branch
    default: "main"
  - name: multi-tenancy-gitops-url
    default: 'https://github.com/ocaso-demo/multi-tenancy-gitops.git'
  - name: multi-tenancy-gitops-branch
    default: master
  - name: debug
    default: "False"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: new-roks-cluster-
    spec:
      pipelineRef:
        name: new-roks-cluster
      params:
      - name: cluster-name
        value: $(tt.params.cluster-name)
      - name: git-new-roks-url
        value: $(tt.params.git-new-roks-url)
      - name: git-new-roks-branch
        value: $(tt.params.git-new-roks-branch)
      - name: multi-tenancy-gitops-url
        value: $(tt.params.multi-tenancy-gitops-url)
      - name: multi-tenancy-gitops-branch
        value: $(tt.params.multi-tenancy-gitops-branch)
      - name: debug
        value: $(tt.params.debug)