apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-credentials
spec:
  data:
  - secretKey: gitUser
    remoteRef:
      key: 62124714-8018-807b-32e1-9991e7e04976
  - secretKey: gitToken
    remoteRef:
      key: 8bae6387-a4fb-2ce6-15b5-fe6b4355a848
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: git-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GIT_USERNAME: "{{ .gitUser | toString }}"
        GIT_PRIV_TOKEN: "{{ .gitToken | toString }}"