apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-apikey
spec:
  data:
  - secretKey: ibmAPIKey
    remoteRef:
      key: 2d7a7bd8-3537-bf07-f27b-09909084e652
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-apikey
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        IBM_APIKEY: "{{ .ibmAPIKey | toString }}"